"""Prompt loader + placeholder substitution.

Prompts live as `.md` files in `<repo>/prompts/`. Each one declares slots like
`{{USER_CONTEXT}}`, `{{TRIAGE_PROPOSAL_SCHEMA}}`. We resolve those at runtime
against the current user-context and committed schemas.

`_shared.md` is loaded by every agent prompt — it carries the invariants and
the user_context block.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

from . import paths

REPO_ROOT = Path(__file__).resolve().parents[2]
PROMPTS_DIR = REPO_ROOT / "prompts"
SCHEMAS_DIR = REPO_ROOT / "schemas"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


@lru_cache(maxsize=32)
def load_template(name: str) -> str:
    return _read(PROMPTS_DIR / name)


@lru_cache(maxsize=32)
def load_schema(name: str) -> dict[str, Any]:
    return json.loads(_read(SCHEMAS_DIR / name))


def load_user_context() -> str:
    """Read the user-context.md the user filled in. Falls back to the template
    so agents always have *something* to ground on."""
    user_copy = paths.config_dir() / "user-context.md"
    if user_copy.exists():
        return _read(user_copy)
    template = REPO_ROOT / "config" / "user-context.template.md"
    if template.exists():
        return _read(template)
    return "(user context not yet configured)"


def load_few_shot() -> str:
    """Few-shot examples regenerated by P5's review loop. Empty until then."""
    p = REPO_ROOT / "prompts" / "few-shot-examples.md"
    return _read(p) if p.exists() else "(none yet — early run)"


def render(
    template_name: str,
    *,
    user_context: str | None = None,
    few_shot: str | None = None,
    schemas: dict[str, str] | None = None,
    extras: dict[str, str] | None = None,
) -> str:
    """Load `<template_name>` and substitute placeholders.

    Built-in slots:
      {{USER_CONTEXT}}, {{FEW_SHOT_EXAMPLES}}

    Schema slots: every key in `schemas` becomes
      {{<KEY>}} → json.dumps(load_schema(<value>))

    Free slots: every (key, value) in `extras` becomes {{<KEY>}} → <value>.
    """
    body = load_template(template_name)
    body = body.replace("{{USER_CONTEXT}}", user_context or load_user_context())
    body = body.replace("{{FEW_SHOT_EXAMPLES}}", few_shot or load_few_shot())

    for slot, schema_file in (schemas or {}).items():
        body = body.replace(
            "{{" + slot + "}}",
            json.dumps(load_schema(schema_file), indent=2),
        )

    for slot, value in (extras or {}).items():
        body = body.replace("{{" + slot + "}}", value)

    return body


def compose_system_prompt(agent_template: str, **kwargs: Any) -> str:
    """Concatenate `_shared.md` + the agent's task prompt."""
    shared = render("_shared.md", **kwargs)
    body = render(agent_template, **kwargs)
    return f"{shared}\n\n---\n\n{body}"
